### ISSUE TITLE
update score-db readme

### ISSUE THREAD

**Issue by jrknezha** [noaa-psd/score-db#15]
[score-db](https://github.com/NOAA-PSL/score-db) has an existing README that covers a lot about the repository. However, it's a little difficult for new users to get started, considering that there are broken links, and it is unclear if the instructions provided are platform specific. A nice to have would be a clearer "getting started" guide, with updated information about anaconda environment and specifics about platforms (hera? AWS? laptop?).

noting that this task corresponds with [this preexisting issue](https://github.com/NOAA-PSL/score-db/issues/8)

**Comment by amschne** [comment]
Addressed by PR #22
