### ISSUE TITLE
cannot filter file counts (by experiment, date range, wallclock time, etc...)

### ISSUE THREAD

**Issue by amschne** [noaa-psd/score-db#32]
The following request is apparently returning all the file counts and is not filtering. This is preventing reliable plotting now that we have multiple experiments with overlapping time periods.

`RequestData(datetime_str='%Y-%m-%d %H:%M:%S', experiment={'name': {'exact': 'scout_runs_gsi3dvar_rod'}, 'wallclock_start': {'from': '2024-01-14 21:21:35', 'to': '2024-01-14 21:21:35'}, 'expt_name': 'scout_runs_gsi3dvar_rod', 'expt_start': '2024-01-14 21:21:35', 'graph_label': 'Number of files', 'graph_color': 'black'}, metric_format_str='file_{metric}', metric='count', time_valid=DateRange(start=datetime.datetime(1994, 1, 1, 0, 0), end=datetime.datetime(2000, 1, 1, 0, 0), current=datetime.datetime(1994, 1, 1, 0, 0), cycle_seconds=0))`

**Comment by jrknezha** [comment]
This has been identified before and as I am aware, this is an isolated bug specific to the file counts only.
